# Generated by Django 3.2.8 on 2021-10-06 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkingId', models.IntegerField()),
                ('checkingName', models.CharField(max_length=50)),
                ('checkingTime', models.DateTimeField()),
                ('checkingDate', models.DateField()),
            ],
            options={
                'db_table': 'CheckingTable',
            },
        ),
        migrations.CreateModel(
            name='TicketListTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketListId', models.IntegerField()),
                ('ticketListName', models.CharField(max_length=50)),
                ('ticketListCreated', models.DateTimeField()),
                ('ticketListUpdates', models.DateTimeField()),
            ],
            options={
                'db_table': 'TicketListTable',
            },
        ),
        migrations.CreateModel(
            name='TicketTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketId', models.IntegerField()),
                ('ticketNumber', models.CharField(max_length=50)),
                ('ticketCustomerName', models.CharField(max_length=50)),
                ('ticketInfo', models.CharField(max_length=100)),
                ('ticketWarningNote', models.CharField(max_length=100)),
                ('ticketUseable', models.IntegerField()),
                ('ticketWarning', models.CharField(max_length=50)),
                ('ticketListId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listTable_tickets', to='backend.ticketlisttable')),
            ],
            options={
                'db_table': 'TicketTable',
            },
        ),
        migrations.CreateModel(
            name='ScanningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanningId', models.IntegerField()),
                ('scanningStatus', models.CharField(max_length=50)),
                ('scanningTime', models.DateTimeField()),
                ('scanningCheckedMannualy', models.BooleanField()),
                ('scanningIssue', models.CharField(max_length=100)),
                ('scanningNote', models.CharField(max_length=100)),
                ('scanningTimesUsed', models.IntegerField()),
                ('scanningTicketNumber', models.CharField(max_length=50)),
                ('scanningCheckingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_history', to='backend.checkingtable')),
            ],
            options={
                'db_table': 'ScanningTable',
            },
        ),
        migrations.CreateModel(
            name='CheckingTicketListRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_id', models.IntegerField()),
                ('checkingListEventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_relation', to='backend.checkingtable')),
                ('checkingTicketListId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_relation', to='backend.ticketlisttable')),
            ],
            options={
                'db_table': 'CheckingTicketListRelationship',
            },
        ),
    ]
